### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by dmitriykharchenko** [nfl/react-helmet#373]
![screenshot 2018-05-03 15 37 05](https://user-images.githubusercontent.com/449604/39606001-fc2f1328-4ee7-11e8-8058-2a4b4bfa7ddc.png)

Hey, 
`HelmetWrapper` uses `deepEqual` to compare props and of course, there are react children components with endless amount of nested objects. 
This seems like a dangerous way to check props equality. Could we turn `HelmetWrapper` into `PureComponent`?

**Comment by srMarquinho** [comment]
Same here. Is there a solution to this?

**Comment by willmcpo** [comment]
Yeh same.

The work around is to not use react children to pass in `<meta>` `<title>` tags, and use the props way:

```
<Helmet
                    title={pageTitle}
                    meta={[
                      {
                        name: 'description',
                        content: pageDescription,
                      },
                    ]}
                  />
```

**Comment by lhtdesignde** [comment]
Just ran into this issue as well. Only saw it happening for Safari and Chrome browsers.

**Comment by nathanforce** [comment]
What is the reasoning behind the deep equality check? Per the React docs...

>We do not recommend doing deep equality checks or using JSON.stringify() in shouldComponentUpdate(). It is very inefficient and will harm performance.

**Comment by dmitriykharchenko** [comment]
@jaredLunde not sure how that could speed up `deepEqual` in `shouldComponentUpdate`
https://github.com/nfl/react-helmet/blob/c102586229549650ddb0f9615a42d351a2c7241b/src/Helmet.js#L93

**Comment by jaredLunde** [comment]
@dmitriykharchenko Sorry, that was a reference to the `Uncaught RangeError: Maximum call stack size exceeded` error and presumably https://github.com/nfl/react-helmet/issues/373#issuecomment-392650715 - not anything perf related.

**Comment by dmitriykharchenko** [comment]
@jaredLunde this error happens because ReactHelmet compares props with deepEqual and when there are children in props it iterate over children as well and since those children are React components (not a plain objects) it simply overflows the stack. The workaround is to avoid providing any children to `<Helmet/>` component, but anyway, deepEqual is still bad.

**Comment by dmitriykharchenko** [comment]
So, I don't see any reason why `<Helmet/>` needs a `key` prop

**Comment by jaredLunde** [comment]
@dmitriykharchenko Gotcha! Well in that case, `key` solves the problem because deepEqual never gets called in `shouldComponentUpdate` as the component re-mounts instead of updating. Hence, no stack overflow. Was very useful in my case.

**Comment by dmitriykharchenko** [comment]
Hm, interesting. Do you have a link to read more about re-mounts of keyed elements?

**Comment by jaredLunde** [comment]
https://reactjs.org/docs/reconciliation.html#keys

Essentially, when the key changes it tells the reconciliation algorithm that the element in the new tree is different from the element in the old tree. If the new key isn't in the children in old tree, a new component is mounted. If the new key was in the children in the old tree the element will be re-used.

**Comment by dmitriykharchenko** [comment]
Aha, you mean that you have to update that key on every render. 
Yep, that seems faster than deepEqual, but still not quite clean as fix deepEqual or avoid children.

**Comment by jaredLunde** [comment]
Well, you only have to update the key when the underlying children change. In my case that happens when that particular view URL changes, but you can use any string representation. Maybe someone has a react-router match.params change which updates the title or meta information - that'd be a good spot to use `key` IMO. Anything where state affects the children.

**Comment by jaredLunde** [comment]
It might not work in some cases. Either way I think we're all in agreement that deepEqual is a bad practice in sCU.

**Comment by piotrblasiak** [comment]
This is a really bad bug - as the props way is not even the documented recommended way to pass metadata to helmet, and there is no other workaround.

**Comment by theKashey** [comment]
Just replace _it_ by https://github.com/FormidableLabs/react-fast-compare

**Comment by ivan-kleshnin** [comment]
Why this is still not adressed? Just remove `deepEqual` check and voila.

**Comment by ivan-kleshnin** [comment]
1) `key` trick doesn't help in all cases
2) Library still crashes in 5.2.0

This bug is devastating. Time to find another library? 😢

**Comment by gregmartyn** [comment]
@ivan-kleshnin
https://github.com/staylor/react-helmet-async

**Comment by tmbtech** [comment]
https://github.com/nfl/react-helmet/pull/402 was merged into master. I would like to get the roll-up PR merged and we can release a beta version for feedback.

**Comment by kambing86** [comment]
> I have the same problem...............
> Why is this closed?

I believe it's merged to `master` branch, we need to wait them to release a new version

**Comment by rbalicki2** [comment]
FWIW I had this issue when running nightwatch / magellan tests. The offending code was in a HOC

```diff
+  const helmet = <Helmet><style key={styles.__hash}>{styles.__css}</style></Helmet>;
+
   const EnhancedComponent = props => (<Fragment>
-    <Helmet>
-      <style key={styles.__hash}>{styles.__css}</style>
-    </Helmet>
+    { helmet }
```

Fingers crossed this will improve performance as well.

**Comment by tmbtech** [comment]
Merged in master, but not yet release. Reopening and will close once it gets published to NPM.

**Comment by dmitriykharchenko** [comment]
Well, I fixed that by removing helmet and implementing my own little lib. 
It works pretty well with SSR including streaming rendering.  If anybody interested, let me know, I'll open source it.

**Comment by donaldpipowitch** [comment]
Looking forward to a release 😍 We have this problem as well and just tracked down the issue.

**Comment by catamphetamine** [comment]
@donaldpipowitch 
Think about this: the fix has been merged for a month now and the maintainters of the library still don't care at all.
They could have released this easy fix for a month now and you'd never have to waste any development work hours to track down this weird bug.
Still, they don't care and they continue to knowingly waste the time of developers all over the world just because the maintainers of this library are too lazy and ignorant.

**Comment by tmbtech** [comment]
> Still, they don't care and they continue to knowingly waste the time of developers all over the world just because the maintainers of this library are too lazy and ignorant.

We are volunteers and I was on paternity leave (returned last tuesday). Please be civil, we are all human. 

You are also welcome to pull from master, copy and paste the code into a vendor folder and use as is. Or use a different package entirely, react-helmet-async looks promising https://github.com/staylor/react-helmet-async.

**Comment by tmbtech** [comment]
Updating for visibility. 

We had some organizational changes and I need to get permission in order to publish to NPM. While that is in progress, we have published to our internal nexus servers for testing.

Stay tuned. v.6.0.0-beta is coming.
We had to bump a major version because we removed the default export and migrated to rollup.js for better bundling support. 

thank you all.

**Comment by kambing86** [comment]
> @donaldpipowitch
> Think about this: the fix has been merged for a month now and the maintainters of the library still don't care at all.
> They could have released this easy fix for a month now and you'd never have to waste any development work hours to track down this weird bug.
> Still, they don't care and they continue to knowingly waste the time of developers all over the world just because the maintainers of this library are too lazy and ignorant.

I can understand why this guy is frustrated, given that there is no new release for this package more than a year, but I don't agree on how he diss the maintainers or contributers.

I think you guys should have released a patched version for v5 without the rollup.

Even with rollup, there is no breaking change for us to use v6 as well, have no idea why need to bump the major version

**Comment by theKashey** [comment]
I few months ago (when I failed to use this library) - I wrote another one. It's not a drop in replace due to different design (does not create title/meta tags), but could save your day - https://github.com/theKashey/react-push-channel

**Comment by raajnadar** [comment]
@kambing86 is right a patch version will be great at least we can publish the changes to our production application without any nasty hacks to fix this issue.

**Comment by grsmvg** [comment]
My application crashes frequently due to this bug. If this bug isn't resolved before our product launch, I'm forced to replace it with another lib / my own implementation 😕

I guess it's not too hard to release a v5 patch? Has nothing to do with the current work on v6 right?

**Comment by mandazi** [comment]
I came across this issue as well.  Looking forward to the next release with the fix.

**Comment by szimek** [comment]
For some strange reason it happens just for one person in our office, so we haven't noticed it during development and tests. Any chance of releasing the beta version soon? :)

**Comment by nickensoul** [comment]
Hello guys.
Any news to just publish patched version to NPM?

**Comment by donaldpipowitch** [comment]
Please give @tmbtech a rest or pay him money for working on this issue. Everyone can fork this lib and patch the code or switch to react-helmet-async or use an object for configuration. There are a lot of alternatives.

**Comment by saiichihashimoto** [comment]
Wow, people are rude.

**Comment by nickensoul** [comment]
Ok, I can to pay something. What the cost you’re talking about?
We just need a working package, and we know what the “open source” means.

**Comment by theKashey** [comment]
Dont forget - you may fork this repo and publish as `@yourname/react-helmet`.
The problem is already solved, fix is in the master branch - just not published to `npm`.

**Comment by tmbtech** [comment]
Hi all, Quick update.

@cwelch5 and I Got the required permission to NPM. We will be publishing to NPM today or tomorrow. 

because the thread is getting a little out of hand, I'm closing and locking the thread. I will be adding a code of conduct and other community support documentation. https://github.com/nfl/react-helmet/issues/424

Thank you all, and thank you for being apart of the community.
